name: Build on Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: src-tauri/target/release/bundle/msi/boxcluster-visualization_0.0.0_x64_en-US.msi
        asset_name: boxcluster-visualization
        asset_content_type: application/x-ms-installer
